### PR TITLE
add destroy() method

### PR DESCRIPTION
**Pull request by atk**
+ events refactoring
+ gzip size optimizations

### CODE REVIEW

**Comment by jaredreich** [comment]
Not related to any issue or end goal.

**Comment by jaredreich** [comment]
Thanks! Not a fan of this code though, will fix independentl, tracking #112.

**Comment by atk** [comment]
Thank you for your feedback. I don't want to waste your time, but if you can spare a bit of it to write a comment what you didn't like about my code, I would appreciate it.

**Comment by jaredreich** [comment]
@atk Tons of unnecessary code changes, too many new additions. Unnecessary style change. Removing the local variables for `queryCommandState` and exec funcs like `formatBlock` that are there for a reason, which is to make the output bundle smaller.

**Comment by atk** [comment]
Thanks for your comment, very much appreciated.

**Pull request closed without merging**
