### PR TITLE
Adding Trumbowyg

### PR DESCRIPTION
**Pull request by brandonsueur**

### CODE REVIEW

**Comment by leeoniya** [comment]
it looks like Trumbowyg has a jQuery dependency

**Comment by Gynidark** [comment]
here !

**Comment by lance0** [comment]
The point is to be dependency free and small, adding jQuery is against the grain.

**Comment by Gynidark** [comment]
The goal is above all to show the alternatives, right ? ;)

**Comment by jaredreich** [comment]
We can leave this open, it should be added, thanks :)

**Pull request closed without merging**
