### PR TITLE
Add font-size buttons issues/45

### PR DESCRIPTION
**Pull request by bcolucci**
https://github.com/jaredreich/pell/issues/45

### CODE REVIEW

**Comment by sgruhier** [comment]
Did you test Chrome? I doesn't work for me.```queryCommandValue('FontSize')```returns false

**Comment by bcolucci** [comment]
Ho... @sgruhier  strange... I've tested it, yep on Chrome.
[https://ibb.co/jsDE0H](https://ibb.co/jsDE0H)

**Comment by sgruhier** [comment]
do you use styleWithCSS or not?

**Comment by jaredreich** [comment]
@sgruhier there is no capital `F`, it's `fontSize`... try `queryCommandValue('fontSize')`

**Comment by jaredreich** [comment]
Will be covered in v2 work: https://github.com/jaredreich/pell/projects/1#card-8535962

**Pull request closed without merging**
