### PR TITLE
Added Counter

### PR DESCRIPTION
**Pull request by fahmidme**
I’ve added an action that counts the characters as the user types.

### CODE REVIEW

**Comment by vincentorback** [comment]
For me, adding stuff like this removes the purpose of pell, being the very lightweight library it is.
I think this should be added as an addon, either in your own project or as some sort of plugin to pell.

**Comment by fahmidme** [comment]
Well, that's why people can add it as an action. If they don't need it, they just don't add the action. And code wise, it only adds a few lines of code.

**Comment by YingshanDeng** [comment]
@fahmidme you just use `String.prototype.length` to count the characters, it maybe not always right! Such as when I type a emoji in it! Consider my [EmojiCharString](https://github.com/YingshanDeng/EmojiCharString), it will work well with unicode emoji.

**Comment by jaredreich** [comment]
Unfortunately I believe this shouldn't be part of the core lib. Thanks for your PR though, good luck extending and customizing pell for your own needs! 😄

**Pull request closed without merging**
