### PR TITLE
undo redo added

### PR DESCRIPTION
**Pull request by sabareeshkk**
added two new functionality undo and redo.

### CODE REVIEW

**Comment by RedFoxCode** [comment]
Duplicate of #55

**Comment by jaredreich** [comment]
@RedFoxCode 👍

**Comment by sabareeshkk** [comment]
thank you. it was my first contribution attempt @jaredreich  @RedFoxCode

**Comment by jaredreich** [comment]
Hey, no problem at all. Your PR was actually great! It's just for this specific thing, I've implemented custom actions just to keep the core lib as small as possible.

Thanks for your time and effort!

**Comment by sabareeshkk** [comment]
Thank you..

**Pull request closed without merging**
